mxpv/podsync

cmd/podsync/updater.go, pkg/ytdl/ytdl.go
This solves #50.
When `youtube-dl` downloads the original file from youtube it's using the given output template to name the file.
Currently when podsync asks it to download a file and convert it to audio with an output template like `/path/episodeip.mp3`; this causes the original file to be downloaded as  `/path/episodeip.mp3`. Which leads to `ffmpeg` using it as both input and output; this causes `ffmpeg` to exit immediately saying output file already exists. 
As a result, all the files stay as `webm` video files named as `[episodeid].mp3`s. These can't be served by itunes etc.
To reproduce:
```
[server]
port = 80
hostname = "http://localhost"
data_dir = "./data/"
[tokens]
youtube = "[YOUTUBE_TOKEN]"
[feeds]
[feeds.arsimet]
url = …
```
=> Use youtube-dl output template with extension parameter #50

Dockerfile
This fixes "ERROR: Signature extraction failed" issue
=> Update to latest Youtube Downloader version

README.md, pkg/config/config.go, pkg/model/feed.go, pkg/ytdl/options.go, pkg/ytdl/options_audio.go, pkg/ytdl/options_audio_test.go, pkg/ytdl/options_video.go, pkg/ytdl/options_video_test.go, pkg/ytdl/ytdl.go
I tried to solve the problem that I wrote in the issue #74 
I did make refactoring of code about generate arguments for the `youtube-dl` and added new optional param in config.
what do you think?
=> #74 limit maximal resolution of videos

cmd/podsync/main.go, cmd/podsync/updater.go
Scheduling is wrongly implemented, as consequence all scheduled jobs (functions) will just update the last feed instead of the corresponding one. This is because the variable feed is overwritten inside the loop. 
The fix is based in the former code before cron functionality was added.
=> Fix Cron schedule

cmd/podsync/updater.go, pkg/ytdl/ytdl.go
When trying to deploy podsync on a DigitalOcean droplet, I faced with this error:
`youtube-dl error: /tmp/podsync-119127838/17gpOMhVlas.%(ext)s  error="failed to execute youtube-dl: exit status 1"`
There was nothing more in the log that would allow to diagnose the problem further which was not very helpful. This PR makes it a bit easier by explicitly logging a message if a '429 Too Many Requests' error was detected or otherwise dumping the stdout from the youtube-dl command.
(Side note in case someone finds this by googling the error: turns out that due to DO's unique IPv6 allocation policy the /64 block ends up being shared by multiple droplets. Most likely Google considers a /64 block as one user (as it should be) and applies combined rate limits to it. The remedy here is to force …
=> Improve youtube-dl logging

README.md, cmd/podsync/main.go, go.mod, go.sum, pkg/config/config.go, pkg/db/badger.go, pkg/model/defaults.go
Currently the logging is done via printing to the standard output. When running podsync as a background service for a long time this becomes a problem because there is no way to delete old logs without restarting the service.
This PR adds support for log rotation using [lumberjack](https://github.com/natefinch/lumberjack ). The logging is controlled by an option section in the log file. If this section is not present, the current behaviour is maintained.
=> Support log rotation

Dockerfile, cmd/podsync/main.go, pkg/ytdl/ytdl.go
In the right way we need make update by cron with lock and stop downloader goroutines.
I can't do it at the moment, but i think we can call selfupdate on start. 
Until selfupdate by timer not implemented we can fix it by stop and start again 🤷‍♂️
=> SelfUpdate for youtube-dl #119

README.md, cmd/podsync/updater.go, pkg/config/config.go
I'd like to filter out episodes with certain keywords in the title or description. Because Go's regexp engine does not support negative lookaheads it is not possible to do this just by specifying a regexp for title.
I considered the following approaches:
- Switching to a different regexp engine (extra dependency, not good).
- Introducing a special syntax for negative filters, e.g. prepending the filter regexp with '!' (hacky).
- Adding separate negative filters.
In the end I've decided in favour of the last approach. This PR adds negative filters for title as well as positive and negative filters for description.
=> Implemented negative filters for title and description.

pkg/feed/xml.go
Certain podcast clients (e.g. Pocket Casts) have issues correctly parsing podcast entries when the provided XML feed does not sort items in descending order based on the entry pubDate.
Podsync's constructed XML feeds do not appear to sort based on pubDate, resulting in unpredictable feed parsing.
The ability to determine the order of the feed's entries based on a user-defined parameter (in this case, pubDate) should help maximize compatibility with podcast clients.
=> Issue#133 Fixed episodes out-of-order in XML;

cmd/podsync/updater.go
If an episode was not dowloaded because it did not match filters, it is still counted towards the limit during cleanup. This PR makes sure only downloaded episodes are counted.
=> Only consider downloaded episodes when cleaning

cmd/podsync/updater.go, pkg/db/badger.go, pkg/db/storage.go
I've run into the following issue: a youtube stream was initially announced, got into podsync db, then it was deleted. However, because it was still in the db, podsync was trying to download it every time.
This PR deletes episodes that have not been downloaded for some reason (either due to the situation described above or because they did not match the filters) and are no longer available in the feed.
Also, when cleaning up an episode its title and description are set to "" to conserve some space. I probably should have split this into two, happy to do so if you don't like this change.
=> Cleanup improvements

README.md, pkg/config/config.go, pkg/ytdl/ytdl.go, pkg/ytdl/ytdl_test.go
This allows inserting arbitrary extra arguments into the youtube-dl command-line within each podcast feed entry. This allows, for example, requesting that youtube-dl embed subtitles and captions into the video file, or configuring additional postprocessor arguments.
No effort has been made to make sure no incompatible arguments are provided, with the expectation that the end-user will understand what's possible, and that this is an option expressly for advanced users.
I’ve confirmed that the mp4 output from youtube-dl with the included example settings does indeed embed captions of whatever sort is available, and that the resultant video subtitles, of both sorts, then work in Apple Podcasts.
This would fix #162, and theoretically also #136!
=> Allow additional youtube-dl arguments

pkg/ytdl/ytdl.go, pkg/ytdl/ytdl_test.go
This pull request improves the portability of the video.
Very occasionally, YouTube publishes videos that combine the AV1 codec and MP4 containers.
AV1+MP4 video was downloaded when I specified the `quality = "low", format = "video"` option (see below).
```bash
$ youtube-dl -f 'worstvideo[ext=mp4]+worstaudio[ext=m4a]/worst[ext=mp4]/worst' DIe_PXlpRd0 --output 'video_%(vcodec)s.%(ext)s'
```
Most podcast players don't support the AV1 codec, so I changed to select H.264 (AVC) codec first.
=> Use H.264 codec first

pkg/config/config.go, pkg/feed/xml.go
Support overwriting title, author and description of feed in config.toml
Fixes #176
=> Support overwriting title, author and description of feed

README.md, cmd/podsync/server.go, pkg/config/config.go, pkg/config/config_test.go, pkg/model/defaults.go
Add Server.path and Server.bindAddress two options to special http server handle path and Bind Address.
=> Add server bind option

pkg/config/config.go, pkg/config/config_test.go, pkg/feed/xml.go
Some users were saying their podcasts were getting rejected since `podcast.IOwner` wasn't being set.  This PR adds that functionality to issue #171.
* Did not disturb existing custom Author string, as users may already be using that (wasn't sure on the backwards compatibility with this repo).
* "Name" needed a prefix, since there was already Title and Description.  Picked `Owner` for now.
* Added to existing Unit Test to ensure it gets set when custom config is used.
* Formatted the TOML in the tests to be more pretty.  :-)
NOTE: I do not have a way to test this as I do not use this repo. This is just a drive-by PR to help the authors.
=> Add Podcast Owner Custom Definitions

README.md
Closes #184
Also removed extra `}` in `IMAGE_URL` of `cover_art`.
=> readme: demonstrate new custom fields in example config.

Dockerfile
Does _not_ close #191, but a temporary solution.
WARN: updating youtube-dl will fail.
```
It looks like you installed youtube-dl with a package manager, pip, setup.py or a tarball. Please use that to update.
```
Instead, to update, use the cmd:
```
apk --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main add youtube-dl
```
I don't know how to do this in go, and if so, the binary needs a switch, if run from docker, indicating that it shall be upgraded via alpine's paman instead.
=> dockerfile: source youtube-dl from alpine repos

Dockerfile
Command output, or `logs` on the docker container results in a garbled banner. Disable printing it for docker.
=> Dockerfile:add `--no-banner`.

Dockerfile, Makefile
Current docker image requires all golang tools to be installed on the host machine.
This change moves the compilation part to the docker image, allowing any machine with docker installed to build podsync
=> build podsync inside docker

Dockerfile, docker-compose.yml
readd `WORKDIR /app`
`config.toml` uses relative path, from the current directory, `$PWD` by default is `/`.
commit f337f6c8b16acad6f6a86648f72061e098652040
removed `WORKDIR /app`, and `/config.toml` was used instead of `/app/config.toml`.
The change was breaking, unexpected and undocumented.
As users already mount `/app/config.toml`, revert to using it.
Closes #270
=> fixup: Dockerfile: reinstate location of config.toml

pkg/builder/youtube.go
To actually include the `Custom.CoverArtQuality` field from feed config into the feed query model.
This fixes #197.
=> Fix cover art quality config and default being ignored

config.toml.example, pkg/builder/youtube.go, pkg/feed/config.go, pkg/feed/xml.go, pkg/model/feed.go
This fixes #188 
According to https://support.google.com/podcast-publishers/answer/10315648?hl=en&ref_topic=9476061, `<itunes:block>` also prevents feed from being added to Google's aggregator, so `<googleplay:block>` is not neeeded.
=> add support to set feed as private

cmd/podsync/main.go
This fixes #220 and fixes #242.
I did not encounter this myself, but based on the error call stack provided, the error seems to be due to a nil logger being passed to [`cron.SkipIfStillRunning`](https://github.com/robfig/cron/blob/v3.0.1/chain.go#L78).
If the next update occurs before the current update finishes, the nil logger is used without check and triggers the nil pointer dereference error.
=> Fix nil pointer dereference for cron

cmd/podsync/main.go, pkg/fs/local.go
This fixes #322.
1. The struct tag for config `storage.local.data_dir` was marked as yaml while we are using toml (So GitHub Copilot managed to escape from my check and picked its favorite config file format)
2. Need to make sure that no defer block get executed before the `errgroup.Wait()` block, i.e. the `errgroup.Wait()` block need to be last one in, first one out.
Maybe we need some kind of integration test to catch things like regression 2 in the future?
=> Fix two regressions introduced by PR #317

config.toml.example, pkg/feed/config.go, pkg/feed/xml.go
This will override the default link (usually the URL address) in the generated RSS feed with another link.
Before:
```
<rss version="2.0" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd">
<channel>
<title>Level1News</title>
<link>https://www.youtube.com/channel/CHANNEL_NAME_TO_HOST</link>
<image>
<link>https://www.youtube.com/channel/CHANNEL_NAME_TO_HOST</link>
</image>
```
After:
```
<rss version="2.0" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd">
<channel>
<title>Level1News</title>
<link>https://example.org</link>
<image>
<link>https://example.org</link>
</image>
```
fixes #233
=> Override the default link

pkg/feed/xml.go, services/update/updater.go
Remove the files before updating the XML feed, so that the files deleted in current update do not show up in the XML feed. I eyeballed and made sure that `u.cleanup` does not rely on the state of `u.buildXML` and `u.buildOPML`, but you might want to double check.
=> Clean up episodes before generating XML feed

cmd/podsync/config.go, cmd/podsync/main.go, config.toml.example
Allow to enable debug mode by setting the value of `debug = true` in `config.toml > log`
=> Add option to enable debug mode in config.toml

.github/workflows/ci.yml, .github/workflows/release.yml, .goreleaser.yml
This PR contains :
- bump golangci-lint to version v1.50.1 to fix the failed `Check` CI step
- uses Env Vars to build and push Docker Image, so anyone can try to release to their own GHCR/DockerHub repos
- add a condition for the Scheduled builds to only happen from your Git repo, as I assume most people won't want to build nightly builds anyway
PS: The GHCR Repo Name has to be lowercase (see [this error](https://github.com/Th0masL/podsync/actions/runs/3505523564/jobs/5871883670#step:6:63)), but because `github.repository_owner` is case-sensitive (like in my case), it's mandatory to first convert it to lowercase. It's not ideal but that's the only method available so far.
=> Fix broken CI Checks step, use Env Vars to build and push Docker Images

config.toml.example
S3 configuration expects `endpoint_url`, not `endpoint`
=> Fix S3 setting name in example

config.toml.example, pkg/fs/s3.go, pkg/fs/s3_test.go
This is my first attempt on adding prefix support for S3-like storages
I'm not a go person, let me know if something is way off or need improvements.
=> Adding support for S3 prefix

cmd/podsync/main.go, config.toml.example, services/web/server.go
I added three new fields to the Server configuration in order to enable TLS connections. I made sure this was backwards compatible so it won't break any existing configuration files. 
- **tls** - Flag that indicates the server should listen for TLS connections
- **certificate_path** - Full path to the certificate file
- **key_file_path** - Full path to the private key file
=> Add TLS support

cmd/podsync/config.go, cmd/podsync/main.go, pkg/builder/soundcloud.go, pkg/builder/soundcloud_test.go, pkg/builder/vimeo.go, pkg/builder/youtube.go, pkg/builder/youtube_test.go
After using podsync for a long time, I want to make some support to this awesome project to show my thanks.
As my first pull request, I just want to make some minor warning fix.
Variable `feed` collides with imported package name, so I rename `feed` to `_feed`, and before that, I rename `_feed` to another name, such as `cronFeed` in `cmd/podsync/main.go`, `feedCopy` in `pkg/builder/youtube_test.go`
=> fix warning: Variable 'feed' collides with imported package name

pkg/builder/youtube.go
I encountered the same issue as #638, so took a look at the unclosed PR #639. Here's my attempt to cleanly resolve the problem. it still skips adding it to the queue, but instead of checking `ContentDetails`, check the correct field to determine whether it is a premiere video.
=> skip unreleased premiere videos

README.md, docker-compose.yml
The database should probably be mapped outside the container. (I think it also helps when you want to run the container as a non-root user as /app isn't writable by non-root users I think)
=> Include database directory in docker instructions

go.mod, go.sum, pkg/builder/builder.go, pkg/builder/twitch.go, pkg/builder/twitch_test.go, pkg/builder/url.go, pkg/model/link.go
Please keep in mind that I am not a Golang expert. This is my second PR in Go, and the first one was a minor bugfix.
I have had the branch running for a few months now, it's doing fine.
=> Add support for Twitch channels

cmd/podsync/config.go, cmd/podsync/config_test.go, config.toml.example, pkg/feed/config.go, services/update/updater.go
- Implements global cleanup policy configuration as requested in #214
- Changes per-feed cleanup policy to optional pointer to enable inheritance
- Adds comprehensive fallback logic and testing
- Add `Cleanup *feed.Cleanup` field to main Config struct
- Change per-feed `Clean Cleanup` to `Clean *Cleanup` (pointer for optional inheritance)
- Add fallback logic in `applyDefaults()` to apply global policy when feed doesn't specify its own
- Add nil check in cleanup function to handle feeds without cleanup policies
- Maintain backward compatibility - existing configurations continue to work unchanged
- Global policy is applied only to feeds that don't specify their own cleanup policy
- Update `config.toml.example` with global cleanup configuration example
- Add comprehensive test suite …
=> Add global cleanup policy configuration

README.md, cmd/podsync/config.go, cmd/podsync/config_test.go, cmd/podsync/main.go, config.toml.example, docs/how_to_get_vimeo_token.md, docs/how_to_get_youtube_api_key.md
Allows users to set API keys through environment variables. This would be helpful to allow checking in config files to git or to simply provide more flexibility.
Closes #504
Closes #225
=> Set API keys through environment variables

pkg/builder/soundcloud_test.go, pkg/builder/url.go, pkg/builder/url_test.go, pkg/builder/youtube.go, pkg/builder/youtube_test.go, pkg/model/link.go
Implements support for YouTube's new @handle URL format. Uses the Search API to resolve handles to channel IDs while maintaining full backward compatibility with existing channel and user URLs.
Users can now use handle URLs in their configurations:
```toml
[feeds.example]
url = "https://www.youtube.com/@mkbhd"
```
Reimplements https://github.com/mxpv/podsync/pull/717
Closes https://github.com/mxpv/podsync/issues/469
Ref https://github.com/mxpv/podsync/pull/475
=> Add YouTube handle support

README.md, docs/how_to_get_vimeo_token.md, docs/how_to_get_youtube_api_key.md
Replace realistic-looking API key examples with generic placeholders to avoid confusion about whether these are real credentials. Addresses feedback from PR #747 comment.
=> Replace realistic API key examples with generic placeholders

.github/workflows/ci.yml, go.mod
- Update go.mod to use Go 1.25
- Update CI workflow to use Go 1.25 for build and test jobs
- Aligns with Dockerfile which already uses Go 1.25
=> Update Go version from 1.24 to 1.25
